### ISSUE TITLE
Feature: check for duplicate files

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-sync-sia#12]
Allot of times users will have the exact same file in multiple folders, uploading exact matching duplicates would be a waste of resources.

**Comment by jkawamoto** [comment]
https://github.com/GooBox/goobox-sync-storj/issues/42 is a related discussion.

**Comment by MeijeSibbel** [comment]
Lets close this for now, there are too many pitfalls with doing something like this.
