### ISSUE TITLE
Exclude system and temporary files

### ISSUE THREAD

**Issue by jkawamoto** [GooBox/goobox-sync-sia#15]
Some files such as `.DS_Store` in mac and `Thumbs.db` in Windows aren't necessary to be synced. Generally, I think hidden files should be excluded to sync, too.

**Comment by jkawamoto** [comment]
It's applied from [v0.0.5](https://github.com/GooBox/goobox-sync-sia/releases/tag/v0.0.5).

**Comment by kaloyan-raev** [comment]
I am not sure if we should avoid syncing hidden files in general. Dropbox synces them and I have found it useful in the past.

Perhaps, we can just filter well-known cache generated hidden files like `.DS_Store` and `Thumb.db`. But, especially in software projects, there are configuration and log files, which are hidden (file name starting with .) that user may expect to be synced.

Moreover, the definition for hidden files on Windows and Unix is completely different, which may also lead to confusion for users.

**Comment by jkawamoto** [comment]
@kaloyan-raev That's a good point. I've researched which files are excluded in other services.

In Dropbox, the following files are excluded:
- system files: `desktop.ini`, `thumbs.db`, `.ds_store`, icons, `.dropbox`, `.dropbox.attr`
- temporary files:
  * a file its name starts with `~$` or `.~`,
  * a file its name starts with `~` and ends with `.tmp`
- files and directories their names end with spaces.

In OneDrive Business, the following files are excluded:
- files and directories their names start with `~`
- invalid files: `*_files`, `*_Dateien`, `*_fichiers`, `*_bestanden`, `*_file`, `*_archivos`, `*_tiedostot`, `*_pliki`, `*_soubory`, `*_elemei`, `*_ficheiros`, `*_arquivo`, `*_dosyalar`, `*_datoteke`. `*_fitxers`, `*_failid`, `*_fails`, `*_bylos`, `*_fajlovi`, `*_fitxategiak`, `*_private`
- files their names end with `.tmp` and `.ds_store`
- sytem files: `desktop.ini`, `thumbs.db`, `ehthumbs.db`

I think for now the Dropbox's rule is good to follow except for `.dropbox` and `.dropbox.attr` (and maybe icons?). 

I also think it's a good time to make a common package to share some logics used by both goobox-sync-storj and goobox-sync-sia. What do you think about it?

**Comment by kaloyan-raev** [comment]
@jkawamoto Thanks for this research!

> I think for now the Dropbox's rule is good to follow except for .dropbox and .dropbox.attr (and maybe icons?).

Sounds like a good start. We can improve it later, if there is any need.

> I also think it's a good time to make a common package to share some logics used by both goobox-sync-storj and goobox-sync-sia. What do you think about it?

Yes, good idea. We have to start merging the two apps sooner or later. Perhaps, we can create a `goobox-sync-common` repo and put the logic for hidden files as the first feature.

**Comment by jkawamoto** [comment]
I created `goobox-sync-common` repository and imported your [Utils class](https://github.com/GooBox/goobox-sync-storj/blob/master/src/main/java/io/goobox/sync/storj/Utils.java). I also add [isExcluded](https://github.com/GooBox/goobox-sync-common/blob/master/src/main/java/io/goobox/sync/common/Utils.java#L112) to check file names match the Dropbox's excluding rule.
