### ISSUE TITLE
Add sync-sia to windows firewall at startup

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-sync-sia#38]
This will prevent messages like this:

![image](https://user-images.githubusercontent.com/11735738/35175430-f15462de-fd73-11e7-85b9-9a2c605b2523.png)

This is also true for the community-gui release, users there will get the same error.

**Comment by jkawamoto** [comment]
It seems to be related to https://github.com/GooBox/goobox-community-gui/issues/26, but in the above case, siad instead of sync-sia-app was blocked. I guess we or sia needs to sign siad.exe.
