### ISSUE TITLE
Bootstrap to reduce blockchain sync time

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-sync-sia#4]
We should bootstrap the blockchain (download it) to significantly reduce sync times.

**Comment by MeijeSibbel** [comment]
https://github.com/NebulousLabs/Sia/blob/4128075f05ee3e134a1a35397a571595a9f55fdf/modules/gateway.go#L22

**Comment by jkawamoto** [comment]
Implemented in https://github.com/GooBox/goobox-sync-sia/commit/43973c4a1d40e176e5c2b0228b536e2fcdfb3c66.

**Comment by MeijeSibbel** [comment]
Thanks, feel free to close any issues when implemented.
