### ISSUE TITLE
Don't plug into existing siad.exe instance from sia-UI

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-sync-sia#48]
Users have reported that when they are already running their sia-UI wallet and start goobox, it will allocate all their funds to storage. This is a problem as it will cause all their funds to get "locked".

**Comment by jkawamoto** [comment]
True. Our siad should run with different port numbers.

**Comment by jkawamoto** [comment]
Commit 623b40a06bb97368300f3b0bdc940b2596c08e68 fixed this issue.
