### ISSUE TITLE
Setup Travis

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-sync-sia#7]

**Comment by jkawamoto** [comment]
Commit db4fa5fcd2dfe73f3d208452c81b8f9f20e59083 includes `.travis.yml`.

**Comment by jkawamoto** [comment]
If we can use [AppVeyor](https://www.appveyor.com/) to run tests in Windows, it would be helpful, too.

**Comment by jkawamoto** [comment]
Commit 422ff78dbed40cf8aae89875dac2e67910589d0d implements [AppVeyor](https://www.appveyor.com/) configuration.
