### ISSUE TITLE
Check if SIA-daemon is already running and if SIA config/blockchain files already exist

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-sync-sia#9]
As mentioned by jkawamoto, if the sia-daemon is already running because someone is already running the SIA-GUI, it is best to use this instead of running a completely new daemon instance. Though we have to be careful, if they turn off the GUI, our app will stop to function so if they do turn it off, we should automatically start our own sia-daemon instance. Same thing applies for both the blockchain files and config files. If they already were running the SIA-GUI the app should recognize this and prompt the user if they want to import their sia-GUI "account". This also prevents the app from having to download the entire blockchain to a separate folder and thus wasting the user's space.

**Comment by jkawamoto** [comment]
Implemented in https://github.com/GooBox/goobox-sync-sia/commit/09ba94873f94fbd2511f11ef87279aab3a3a3267.

**Comment by MeijeSibbel** [comment]
Thanks, closing
